// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Config } from "./Config";
import type { ContentEntry } from "./ContentEntry";
import type { ContentUpdateInfo } from "./ContentUpdateInfo";
import type { FabricLoaderSummary } from "./FabricLoaderSummary";
import type { FileEntry } from "./FileEntry";
import type { InstanceSummary } from "./InstanceSummary";
import type { JavaInstall } from "./JavaInstall";
import type { LauncherLogFile } from "./LauncherLogFile";
import type { LogFile } from "./LogFile";
import type { ModpackSummary } from "./ModpackSummary";
import type { ModrinthHit } from "./ModrinthHit";
import type { ModrinthProject } from "./ModrinthProject";
import type { ModrinthVersion } from "./ModrinthVersion";
import type { PresencePreview } from "./PresencePreview";
import type { PresenceStatus } from "./PresenceStatus";
import type { Preset } from "./Preset";
import type { ProfileSummary } from "./ProfileSummary";
import type { ResolvedPaths } from "./ResolvedPaths";
import type { Screenshot } from "./Screenshot";
import type { SkippedEntry } from "./SkippedEntry";
import type { VersionSummary } from "./VersionSummary";

/**
 * The result of a successfully dispatched `Command`. One variant per
 * `Command` variant.
 */
export type CommandOutput = { "result": "config_shown", paths: ResolvedPaths, config: Config, } | { "result": "installed", instance: string, mc_version: string, } | { "result": "launch_planned", instance: string, command_line: string, } | { "result": "launched", instance: string, pid: number, 
/**
 * Where this run's JVM stdout/stderr were redirected — the process
 * is spawned detached from the frontend's own stdio (see
 * `Session::launch`'s doc comment), so this is how a caller finds
 * the output after the fact.
 */
log_path: string, } | { "result": "instance_listed", instances: Array<InstanceSummary>, } | { "result": "instance_updated", instance: string, } | { "result": "version_listed", latest_release: string, versions: Array<VersionSummary>, } | { "result": "fabric_loader_listed", mc_version: string, loaders: Array<FabricLoaderSummary>, } | { "result": "instance_removed", instance: string, } | { "result": "instance_renamed", old: string, 
/**
 * The new slug.
 */
instance: string, } | { "result": "instance_cloned", source: string, 
/**
 * The new instance's slug.
 */
instance: string, } | { "result": "instance_killed", instance: string, } | { "result": "log_listed", instance: string, logs: Array<LogFile>, } | { "result": "file_listed", instance: string, 
/**
 * The listed folder, normalised (no leading/trailing `/`).
 */
path: string, entries: Array<FileEntry>, } | { "result": "file_contents", path: string, text: string, } | { "result": "file_written", path: string, } | { "result": "file_deleted", path: string, } | { "result": "file_imported", count: number, } | { "result": "launcher_log_listed", 
/**
 * This run's log file name, if it has one.
 */
current: string | null, logs: Array<LauncherLogFile>, } | { "result": "launcher_log_chunk", 
/**
 * Which log was read; `None` when there is none.
 */
file: string | null, text: string, 
/**
 * Byte range of `text` in the file: pass `end` back as `offset`
 * to follow the log, `start` as `before` to page backwards.
 */
start: number, end: number, 
/**
 * The file's size when it was read.
 */
size: number, } | { "result": "launcher_last_session", log: LauncherLogFile | null, } | { "result": "logged" } | { "result": "log_chunk", 
/**
 * Which log was read; `None` when the instance has no logs yet.
 */
file: string | null, text: string, next_offset: number, } | { "result": "modrinth_searched", hits: Array<ModrinthHit>, offset: number, total_hits: number, } | { "result": "modrinth_project_shown", project: ModrinthProject, } | { "result": "modrinth_versions_listed", versions: Array<ModrinthVersion>, } | { "result": "modpack_inspected", pack: ModpackSummary, } | { "result": "content_listed", instance: string, entries: Array<ContentEntry>, } | { "result": "content_installed", instance: string, installed: Array<ContentEntry>, } | { "result": "content_removed", instance: string, filename: string, } | { "result": "content_toggled", instance: string, filename: string, enabled: boolean, } | { "result": "content_imported", instance: string, entry: ContentEntry, } | { "result": "content_identified", instance: string, identified: number, } | { "result": "content_updates_found", instance: string, updates: Array<ContentUpdateInfo>, } | { "result": "java_listed", installs: Array<JavaInstall>, } | { "result": "java_runtime_removed", component: string, } | { "result": "instance_java_shown", instance: string, component: string, major_version: number | null, 
/**
 * Installed runtime version; `None` if not downloaded yet (it
 * downloads before the first launch).
 */
installed_version: string | null, 
/**
 * Where its `java` executable is (or will be).
 */
path: string, 
/**
 * Whether Mojang publishes runtimes for this platform at all.
 */
available: boolean, } | { "result": "screenshot_listed", screenshots: Array<Screenshot>, } | { "result": "screenshot_deleted", path: string, } | { "result": "preset_listed", presets: Array<Preset>, } | { "result": "preset_saved", preset: Preset, 
/**
 * Untracked local files that couldn't be included.
 */
skipped_local: number, } | { "result": "preset_applied", instance: string, 
/**
 * Everything installed, dependencies included.
 */
applied: Array<ContentEntry>, skipped: Array<SkippedEntry>, } | { "result": "preset_deleted", name: string, } | { "result": "preset_renamed", name: string, } | { "result": "preset_exported", path: string, } | { "result": "preset_imported", preset: Preset, } | { "result": "profile_listed", profiles: Array<ProfileSummary>, } | { "result": "profile_added", profile: ProfileSummary, } | { "result": "profile_removed", name: string, } | { "result": "profile_default_set", name: string, } | { "result": "presence_status_shown", status: PresenceStatus, } | { "result": "presence_previewed", preview: PresencePreview | null, } | { "result": "presence_view_set" };
