// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";
import type { DiscordConfig } from "./DiscordConfig";
import type { LauncherView } from "./LauncherView";
import type { ModpackSource } from "./ModpackSource";
import type { PreviewScenario } from "./PreviewScenario";
import type { SearchSort } from "./SearchSort";

/**
 * Every action a frontend can ask for. New variants land milestone by
 * milestone; nothing outside `bananium-api` may add capability that isn't
 * expressed here first (see the frontend contract in CONTRIBUTING.md).
 */
export type Command = { "command": "config_show" } | { "command": "config_set", max_concurrent_downloads: number | null, java_path: string | null, } | { "command": "java_list" } | { "command": "java_runtime_remove", component: string, } | { "command": "instance_java", instance: string, } | { "command": "screenshot_list", instance: string | null, } | { "command": "screenshot_delete", path: string, } | { "command": "install", version: string, name: string | null, fabric_loader: string | null, group: string | null, } | { "command": "version_list", include_snapshots: boolean, } | { "command": "fabric_loader_list", mc_version: string, } | { "command": "launch", instance: string | null, profile: string | null, dry_run: boolean, } | { "command": "instance_list" } | { "command": "instance_set", instance: string, 
/**
 * `Some(0)` clears the cap back to the JVM default (a real 0 MB
 * cap isn't meaningful, so it doubles as the "unset" sentinel
 * rather than needing a nested `Option`); `Some(n>0)` sets it;
 * `None` leaves the current value alone.
 */
ram_mb: number | null, 
/**
 * Replaces the stored extra-JVM-args list entirely when given
 * (an empty `Vec` clears it); `None` leaves the current list
 * alone.
 */
jvm_args: Array<string> | null, 
/**
 * Per-instance Java executable. `Some("")` clears it back to the
 * global setting/auto-detection; `None` leaves it alone.
 */
java_path: string | null, 
/**
 * Library group. `Some("")` ungroups it; `None` leaves it alone.
 */
group: string | null, } | { "command": "instance_set_icon", instance: string, path: string | null, } | { "command": "instance_remove", instance: string, } | { "command": "instance_rename", instance: string, new_name: string, } | { "command": "instance_clone", instance: string, new_name: string, } | { "command": "instance_kill", instance: string, } | { "command": "log_list", instance: string, } | { "command": "log_read", instance: string, file: string | null, offset: number, } | { "command": "file_list", instance: string, path: string, } | { "command": "file_read", instance: string, path: string, } | { "command": "file_write", instance: string, path: string, text: string, create_new: boolean, } | { "command": "file_create_dir", instance: string, path: string, } | { "command": "file_rename", instance: string, from: string, to: string, } | { "command": "file_delete", instance: string, path: string, } | { "command": "file_import", instance: string, path: string, sources: Array<string>, } | { "command": "modrinth_search", query: string, kind: ContentKind, instance: string | null, 
/**
 * Modrinth category slugs, each required (AND).
 */
categories: Array<string>, sort: SearchSort, offset: number, limit: number, } | { "command": "modrinth_project", project: string, } | { "command": "modrinth_versions", project: string, kind: ContentKind, instance: string | null, } | { "command": "modpack_search", query: string, 
/**
 * Modrinth category slugs, each required (AND).
 */
categories: Array<string>, sort: SearchSort, offset: number, limit: number, } | { "command": "modpack_versions", project: string, } | { "command": "modpack_inspect", path: string, } | { "command": "modpack_install", source: ModpackSource, name: string | null, group: string | null, } | { "command": "content_list", instance: string, } | { "command": "content_install", instance: string, kind: ContentKind, project: string, version: string | null, } | { "command": "content_remove", instance: string, kind: ContentKind, filename: string, } | { "command": "content_toggle", instance: string, kind: ContentKind, filename: string, enabled: boolean, } | { "command": "content_import", instance: string, kind: ContentKind, path: string, } | { "command": "content_identify", instance: string, } | { "command": "content_check_updates", instance: string, } | { "command": "content_update", instance: string, projects: Array<string>, } | { "command": "preset_list" } | { "command": "preset_save", instance: string, name: string, kinds: Array<ContentKind>, } | { "command": "preset_apply", preset: string, instance: string, } | { "command": "preset_delete", name: string, } | { "command": "preset_rename", name: string, new_name: string, } | { "command": "preset_export", name: string, path: string, } | { "command": "preset_import", path: string, } | { "command": "profile_list" } | { "command": "profile_add", name: string, } | { "command": "profile_remove", name: string, } | { "command": "profile_set_default", name: string, } | { "command": "discord_config_set", config: DiscordConfig, } | { "command": "instance_set_discord", instance: string, hidden: boolean, } | { "command": "presence_set_view", view: LauncherView, } | { "command": "presence_status" } | { "command": "presence_preview", scenario: PreviewScenario, config: DiscordConfig | null, } | { "command": "presence_reconnect" };
