// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolved configuration: defaults -> `config.toml` -> environment ->
 * caller-supplied overrides (typically CLI flags). Each layer only
 * overwrites the fields it actually sets.
 */
export type Config = { 
/**
 * Upper bound on simultaneous downloads (the download engine's
 * `Semaphore` size); default 8. Peak memory scales with this, not with
 * queue length.
 */
max_concurrent_downloads: number, 
/**
 * TUI theme name; themes are TOML (M2+, not yet implemented).
 */
theme: string, 
/**
 * Explicit JVM path, overriding auto-detection in `bananium_java::find_java`.
 */
java_path: string | null, };
