// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";

/**
 * One installed piece of content.
 */
export type ContentEntry = { kind: ContentKind, 
/**
 * File (or, for an unzipped pack, directory) name without any
 * `.disabled` suffix — the stable key within `kind`'s folder.
 */
filename: string, enabled: boolean, 
/**
 * Display name: the Modrinth project title, or the file name for
 * untracked files.
 */
title: string, 
/**
 * Modrinth project id; `None` for a file not (yet) identified.
 */
project_id?: string | null, version_id?: string | null, 
/**
 * Human-readable version, e.g. `"mc1.21.1-0.6.0"`.
 */
version_number?: string | null, icon_url?: string | null, 
/**
 * `None` for a directory pack, which has no single hash.
 */
sha1?: string | null, 
/**
 * Installed automatically as another project's required dependency
 * rather than chosen directly.
 */
dependency: boolean, };
