// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of content a file is, which decides the folder it lives in.
 */
export type ContentKind = "mod" | "resource_pack" | "shader";
