// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";

/**
 * An installed Modrinth project with a newer compatible version available.
 */
export type ContentUpdateInfo = { project_id: string, kind: ContentKind, filename: string, title: string, current_version: string | null, new_version_id: string, new_version_number: string, };
