// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusDisplay } from "./StatusDisplay";

/**
 * Discord Rich Presence settings. Everything is shown by default; each
 * switch hides one detail. The struct is `serde(default)` so a partial
 * `[discord]` table only overrides what it mentions.
 */
export type DiscordConfig = { 
/**
 * Master switch: off clears the presence and disconnects from Discord.
 */
enabled: boolean, 
/**
 * Show an activity while no game is running (browsing, installing,
 * idle in the launcher); off means presence only while playing.
 */
show_in_launcher: boolean, 
/**
 * Say what's being browsed on Modrinth, down to the project viewed.
 */
show_browsing: boolean, 
/**
 * Show installs and downloads, with a progress bar.
 */
show_tasks: boolean, show_version: boolean, show_loader: boolean, show_loader_version: boolean, show_mod_count: boolean, 
/**
 * The offline username being played as.
 */
show_username: boolean, 
/**
 * The instance's name (in the large image's tooltip).
 */
show_instance_name: boolean, 
/**
 * Put the instance name in the status line itself ("Playing My
 * Survival") instead of "Playing Minecraft 1.21.1".
 */
instance_name_in_status: boolean, 
/**
 * A Modrinth modpack's own icon as the large image.
 */
show_modpack_icon: boolean, 
/**
 * The "elapsed" timer.
 */
show_elapsed: boolean, 
/**
 * "View modpack" / "Get Bananium" link buttons.
 */
show_buttons: boolean, status_display: StatusDisplay, };
