// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything a frontend can be told about while a `Command` runs. Every
 * long-running task reports `Progress` under a stable `task_id`, so every
 * frontend renders progress/cancellation/failure identically without
 * inventing its own scheme.
 *
 * Byte counts are `u64` in Rust but typed as `number` in the generated
 * TypeScript: serde_json emits them as plain JSON numbers, not `bigint`,
 * and no real download approaches 2^53 bytes.
 */
export type Event = { "event": "log", level: string, message: string, } | { "event": "progress", task_id: string, label: string, bytes_done: number, bytes_total: number | null, bytes_per_sec: number, } | { "event": "overall_progress", task_id: string, label: string, 
/**
 * What's being fetched right now (e.g. a maven coordinate or asset
 * path), when downloading.
 */
current_file: string | null, bytes_done: number, bytes_total: number | null, 
/**
 * Average bytes/sec since the job started (total bytes done over
 * total elapsed time, not an instantaneous rate).
 */
bytes_per_sec: number, files_done: number, files_total: number, } | { "event": "task_completed", task_id: string, } | { "event": "task_failed", task_id: string, error: string, } | { "event": "instance_exited", instance: string, exit_code: number | null, };
