// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of a folder in an instance's game directory, as listed by
 * `Command::FileList`.
 */
export type FileEntry = { name: string, 
/**
 * Relative to the game directory, `/`-separated; pass back to the
 * other `File*` commands.
 */
path: string, is_dir: boolean, 
/**
 * Bytes; 0 for folders.
 */
size: number, modified_unix: number, 
/**
 * The real path, for "open with the system" / "show in folder".
 */
abs_path: string, };
