// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One gallery image of a Modrinth project.
 */
export type GalleryItem = { url: string, title: string | null, };
