// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One instance's summary, as surfaced by `Command::InstanceList` — enough
 * for a frontend's instance list without a separate lookup per row.
 */
export type InstanceSummary = { slug: string, name: string, mc_version: string, 
/**
 * `"vanilla"` or `"fabric"`.
 */
loader: string, 
/**
 * The pinned loader release, for a modded instance.
 */
loader_version: string | null, ram_mb: number | null, jvm_args: Array<string>, 
/**
 * Per-instance Java override, if any.
 */
java_path: string | null, 
/**
 * The game directory (`--gameDir`): saves, mods, resource packs,
 * screenshots — what "open folder" should open.
 */
game_dir: string, 
/**
 * Whether `bananium_instance::InstanceStore::is_running` currently
 * sees a live pid recorded for this instance.
 */
running: boolean, };
