// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A usable JVM: a Mojang runtime Bananium downloaded, or one detected on
 * the machine.
 */
export type JavaInstall = { path: string, major_version: number, 
/**
 * `"mojang"` (downloaded into `java/`) or `"system"` (detected).
 */
source: string, 
/**
 * Mojang runtime component, e.g. `"java-runtime-delta"`.
 */
component: string | null, 
/**
 * Mojang runtime version, e.g. `"21.0.7"`.
 */
version: string | null, 
/**
 * Disk used by a Mojang runtime.
 */
size_bytes: number | null, };
