// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which launcher page the user is on, reported by the frontend with
 * `Command::PresenceSetView` so an idle presence can say what they're
 * doing ("Browsing mods", "Looking at Sodium").
 */
export type LauncherView = { "view": "library" } | { "view": "instance", instance: string, } | { "view": "browse", kind: string, } | { "view": "project", title: string, author: string | null, icon_url: string | null, url: string | null, } | { "view": "presets" } | { "view": "screenshots" } | { "view": "accounts" } | { "view": "settings" } | { "view": "about" } | { "view": "other" };
