// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStatus } from "./LogStatus";

/**
 * One launcher log file, as listed by `Command::LauncherLogList`.
 */
export type LauncherLogFile = { 
/**
 * File name (`YYYY-MM-DD_HH-MM-SS[_n].log`); pass back as
 * `LauncherLogRead::file`.
 */
name: string, path: string, size: number, modified_unix: number, status: LogStatus, 
/**
 * One line on how it ended ("Closed: ...", "Crashed: ...", ...);
 * `None` while running.
 */
reason: string | null, };
