// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One launch log file, as listed by `Command::LogList`.
 */
export type LogFile = { 
/**
 * File name; pass back as `LogRead::file`.
 */
name: string, path: string, size: number, modified_unix: number, };
