// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a launcher run ended, read back from its log file.
 */
export type LogStatus = "running" | "closed" | "crashed" | "unclean";
