// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a modpack needs, read from its `modrinth.index.json`.
 */
export type ModpackSummary = { name: string, 
/**
 * The pack's own version, e.g. `"5.3.0"`.
 */
version_id: string, summary: string | null, mc_version: string, 
/**
 * `"vanilla"` or `"fabric"`.
 */
loader: string, loader_version: string | null, 
/**
 * Files downloaded on install (server-only files excluded).
 */
file_count: number, 
/**
 * Why Bananium can't install this pack (e.g. it needs Forge); `None`
 * when it can.
 */
unsupported: string | null, };
