// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where `Command::ModpackInstall` gets its `.mrpack` from.
 */
export type ModpackSource = { "type": "modrinth", project: string, version: string | null, } | { "type": "file", path: string, };
