// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One version of a Modrinth project.
 */
export type ModrinthVersion = { id: string, name: string, version_number: string, 
/**
 * `release`, `beta`, or `alpha`.
 */
version_type: string, date_published: string, downloads: number, game_versions: Array<string>, loaders: Array<string>, 
/**
 * Usable by the instance the listing targeted (always `true` without one).
 */
compatible: boolean, };
