// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Modrinth search result.
 */
export type ModrinthHit = { project_id: string, slug: string | null, title: string, description: string, author: string, icon_url: string | null, downloads: number, follows: number, categories: Array<string>, date_modified: string, 
/**
 * Already installed in the instance the search targeted.
 */
installed: boolean, };
