// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a piece of content stands with Modrinth. Lives in the lockfile
 * next to the rest of the entry's metadata, so a file that appears in a
 * content folder starts out [`ModrinthStatus::Unchecked`] automatically.
 */
export type ModrinthStatus = "unchecked" | "identified" | "not_found";
