// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalleryItem } from "./GalleryItem";

/**
 * A Modrinth project's full details, for a project page.
 */
export type ModrinthProject = { id: string, slug: string | null, title: string, description: string, 
/**
 * Long description, markdown.
 */
body: string, project_type: string, icon_url: string | null, gallery: Array<GalleryItem>, downloads: number, followers: number, categories: Array<string>, license: string | null, updated: string, game_versions: Array<string>, loaders: Array<string>, source_url: string | null, issues_url: string | null, wiki_url: string | null, discord_url: string | null, };
