// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewButton } from "./PreviewButton";
import type { StatusDisplay } from "./StatusDisplay";

/**
 * An activity exactly as Discord will show it (already clamped to
 * Discord's limits), for a frontend to render a look-alike card.
 */
export type PresencePreview = { 
/**
 * The "Playing …" headline: the Discord application's name.
 */
app_name: string, details: string | null, state: string | null, 
/**
 * Image URLs.
 */
large_image: string | null, large_text: string | null, small_image: string | null, small_text: string | null, 
/**
 * Unix milliseconds: "elapsed" counts from `start_ms`; with `end_ms`
 * too, it's a progress bar.
 */
start_ms: number | null, end_ms: number | null, buttons: Array<PreviewButton>, 
/**
 * Which line the member list shows.
 */
status_display: StatusDisplay, };
