// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetEntry } from "./PresetEntry";

/**
 * A saved preset (also its exact on-disk TOML shape).
 */
export type Preset = { name: string, 
/**
 * Minecraft version of the instance it was saved from (informational).
 */
mc_version: string, loader: "vanilla" | "fabric", entries: Array<PresetEntry>, };
