// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";

/**
 * One project in a preset.
 */
export type PresetEntry = { kind: ContentKind, project_id: string, 
/**
 * The version installed when the preset was saved; reused when the
 * target instance can run it.
 */
version_id?: string | null, title: string, icon_url?: string | null, };
