// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the connection to the local Discord client stands.
 */
export type PresenceStatus = { "state": "disabled" } | { "state": "connecting" } | { "state": "connected" } | { "state": "waiting", error: string, };
