// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link button under the activity.
 */
export type PreviewButton = { label: string, url: string, };
