// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A canned situation for previewing presence in settings, so every toggle
 * can be tried without actually launching or installing anything.
 */
export type PreviewScenario = "live" | "idle" | "browsing" | "installing" | "playing";
