// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One saved offline profile (a username to play as).
 */
export type ProfileSummary = { name: string, 
/**
 * The offline UUID vanilla derives from `name` (hyphenated form).
 */
uuid: string, 
/**
 * Whether a launch that doesn't name a profile would use this one.
 */
is_default: boolean, };
