// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The subset of `Paths` surfaced to frontends, for `bananium config show`.
 */
export type ResolvedPaths = { home: string, config_toml: string, store_dir: string, instances_dir: string, java_dir: string, assets_dir: string, };
