// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One screenshot file.
 */
export type Screenshot = { instance: string, instance_name: string, file_name: string, path: string, size: number, taken_unix: number, };
