// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for `Command::ModrinthSearch`.
 */
export type SearchSort = "relevance" | "downloads" | "follows" | "newest" | "updated";
