// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a task does. Part of a task's dedup identity, and lets a frontend
 * find "the install of this project into this instance" among the tasks
 * in flight without guessing from labels.
 */
export type TaskKind = "install" | "modpack_install" | "content_install" | "content_update" | "preset_apply" | "content_identify" | "java_runtime";
