// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a task is waiting for its turn or doing its work.
 */
export type TaskState = "queued" | "running";
