// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskKind } from "./TaskKind";
import type { TaskState } from "./TaskState";

/**
 * One task in the queue, as `Command::TaskList` reports it — enough for a
 * frontend to rebuild its task tray after a reload.
 */
export type TaskInfo = { task_id: string, kind: TaskKind, 
/**
 * What the task is, for people: "Installing Sodium into COB".
 */
label: string, 
/**
 * The instance it works on, when known up front.
 */
instance: string | null, 
/**
 * The Modrinth project it installs, for content and modpack installs.
 */
project: string | null, state: TaskState, 
/**
 * 1-based place in the waiting line; `None` once running.
 */
position: number | null, 
/**
 * The step a running task is on ("Placing modpack files").
 */
phase: string | null, };
