// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Minecraft version from Mojang's manifest.
 */
export type VersionSummary = { id: string, 
/**
 * `release`, `snapshot`, `old_beta`, or `old_alpha`.
 */
kind: string, 
/**
 * ISO-8601 release timestamp.
 */
release_time: string, };
