[package]
name = "bananium-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bananium-tui"
path = "src/main.rs"

[dependencies]
bananium-api = { path = "../bananium-api" }
crossterm = "0.29"
ratatui = "0.30"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
